### ISSUE TITLE
Enum with empty string generates syntax error

### ISSUE THREAD

**Issue by jayvdb** [cyclosproject/ng-openapi-gen#118]
I have a component
```yaml
    TitleEnum:
      enum:
      - Mr
      - Miss
      - Mrs
      - Ms
      - Dr
      - ''
```

It generates
```typescript
/* tslint:disable */
export enum TitleEnum {
  Mr = 'Mr',
  Miss = 'Miss',
  Mrs = 'Mrs',
  Ms = 'Ms',
  Dr = 'Dr',
   = ''
}
```
