### ISSUE TITLE
Precedence and/or logic when using nested allOf and anyOf

### ISSUE THREAD

**Issue by jurgenf** [cyclosproject/ng-openapi-gen#148]
Given the following OpenApi property defintion:
```yaml
PropertyName:
    type: array
    items:
      allOf:
        - $ref: [basic implementation].yaml
        - anyOf:
            - $ref: [concrete implementation 1].yaml
            - $ref: [concrete implementation 2].yaml
```
I expect this to mean: all items have to adhere to definition `[basic implementation]` and any of the referenced concrete implementations.

The generated model has the following typehint:
```typescript
PropertyName: Array<BasicImplementation & ConcreteImplementation1 | ConcreteImplementation2>;
```

Given that the `&` operator precedes the `|` operator this is interpreted as:
```typescript
PropertyName: Array<(BasicImplementation & ConcreteImplementation1) | ConcreteImplementation2>;
```
But I would expect this to be:
```typescript
PropertyName: Array<BasicImplementation & (ConcreteImplementation1 | ConcreteImplementation2)>;
```

I suspect the generated code is incorrect and the `or` parts should be parenthesized. Or is my understanding of the usage of the `allOf`/`anyOf` incorrect?
