### ISSUE TITLE
context:HttpContext parameter is conflicting when having an context query parameter.  

### ISSUE THREAD

**Issue by JeanMeche** [cyclosproject/ng-openapi-gen#238]
The following API definition 

```
/api/v1/admin/email/feedback:
    post:
      parameters:
        - in: query
          name: reply
          description: Email address where Eaton support can contact person
          required: true
          schema:
            type: string
        - in: query
          name: message
          description: Body of email message to be sent
          required: true
          schema:
            type: string
        - in: query
          name: context
          description: UI context, from which page we got the feedback
          required: true
          schema:
            type: string
        - in: query
          name: participate
          description: Indication if user is willing to participate in feedback
          required: false
          schema:
            type: string
      operationId: sendFeedback
      description: Sends feedback email
      summary: Sends feedback email
      tags:
        - AdminApi
```

Will generate this erronous function paramters  : 

```
    sendFeedback$Response(params: {
        reply: string;
        message: string;
        context: string;
        participate?: string;
        context?: HttpContext;
    }): Observable<StrictHttpResponse<void>> {
```

Shouldn't the query parameters be in a separate object and the context in a second parameter  ?
