### ISSUE TITLE
Problem with encoding in enums

### ISSUE THREAD

**Issue by aldonogueira** [cyclosproject/ng-openapi-gen#243]
There is something like this in our openapi file:
```
        OperacaoDetalhe: 
          type: string 
          description: Detalhamento da operação 
          enum: 
            - "Convés" 
            - "Diesel"
            - "Água"
            ...
```
Which generated the following typescript code:
```
  /**
   * Detalhamento da operação
   */
  OperacaoDetalhe?: 'Conv\xE9s' | 'Diesel' | '\xC1gua' | ...
```
Note that the encoding in the comments are OK, but the enums are weird.  

We should probably avoid using accents in enums, but this is something our team can't decide
