### ISSUE TITLE
Parameter's descriptions are html escaped

### ISSUE THREAD

**Issue by kbuntrock** [cyclosproject/ng-openapi-gen#247]
Unlike other "description" properties, parameter's ones are html escaped.

Example :  

```yaml
{
  "name": "petId",
  "in": "path",
  "required": true,
  "description": "Pet's id to retrieve",
  "schema": {
    "type": "string"
  }
 }
```

will generate :  

```ts
/**
* Pet&#x27;s id to retrieve
*/
petId: string;
```

It should be : 

```ts
/**
* Pet's id to retrieve
*/
petId: string;
```
