### ISSUE TITLE
Expected enum instead of string in the output result

### ISSUE THREAD

**Issue by mmza94** [cyclosproject/ng-openapi-gen#252]
It would be great to have the same output as **openapi-generator** produces in case of **enum properties** parsing.

**Yaml snippet:**
```
system-file:
  properties:
    autoStart:
      enum:
      - true
      - false
      - always
      type: string
    ...
```

Generated by **openapi-generator**:
```
export interface SystemFile { 
  autoStart?: SystemFileAutoStartEnum;
  ...
}
export enum SystemFileAutoStartEnum {
    True = 'true',
    False = 'false',
    Always = 'always'
};
```

Generated by **ng-openapi-gen**:
```
export interface SystemFile {
  autoStart?: 'true' | 'false' | 'always';
  ...
}
```

"ng-openapi-gen": "0.23.0"
