### ISSUE TITLE
Support x-operation-name extension

### ISSUE THREAD

**Issue by exejutable** [cyclosproject/ng-openapi-gen#30]
Today if the operationId is repeated add a suffix to the name for example:

```
users:
    get:
        operationId: find
        tags:
            - users
organizations:
    get:
        operationId: find
        tags:
            - organizations

```

this create two  services `users` with the method `find` and the service `organizations` with the method `find_1`. Maybe we can change this to make  the combination of `tag` and `operationId` unique to prevent the suffix in this cases?
