### ISSUE TITLE
Enum serialization with negative values duplicates enum keys

### ISSUE THREAD

**Issue by bzh2610** [cyclosproject/ng-openapi-gen#335]
I have an OpenAPI spec generated in JSON containing the following enum : 

```
 "CustomType": {
   "enum": [0, 1, 2, 3, -1],
   "type": "integer",
   "format": "int32"
 },
```

If I check the custom typescript file generated, I get the following : 

```
export enum ExhibitType {
  $0 = 0,
  $1 = 1,
  $2 = 2,
  $3 = 3,
  $1 = -1,
}
```

Which doesn't compile as we redeclare $1 twice.
Is there any workarround or configuration I missed ?

I can provide a code sandox if needed for reproduction.

**Comment by Colleoni** [comment]
I encounter a similar behaviour with special characters:

```
AgeRangeEnum:
  enum:
  - 18+
  - <18
  type: string
  description: |-
    * `18+` - Adult
    * `<18` - Underage
 ```
 
 which results in 
 ```
 export enum AgeRangeEnum {
  $18 = '18+',
  $18 = '<18'
}
```
